### ISSUE TITLE
Android/Chrome formatting for expiry date and credit card number

### ISSUE THREAD

**Issue by dpattondeloitte** [jessepollak/payment#71] opened 2017-06-22 22:37 UTC
On Pixel, running Android 7.1.2, in Chrome and Samsung S8 running Android running 7.0, also Chrome, ExpiryDate and CreditCard numbers are not formatting.

Steps to reproduce:
1. Use a Pixel or S8 running Android 7 Nougat
2. Open most recent version of Chrome
3. Navigate to http://jessepollak.github.io/payment/example/
4. Use credit card and expiry fields

![photo on 6-22-17 at 4 54 pm](https://user-images.githubusercontent.com/25358088/27459517-e0b1beb2-576b-11e7-8e03-3b4c5eeee77a.jpg)

**Comment by dazaooo** [comment] 2017-09-11 06:21
I have this problem, too

**Comment by silentbugs** [comment] 2017-09-11 18:44
I've dug down this issue. This is happening because this library handles the keyboard events `keypress`, `keydown`, `keyup` etc. Those events work differently on android than they work on other browsers, and this has been known for years.

I tried to fork and fix this by replacing most events with the on `input` event which works exactly as intended, however this library's functionality has been built around the `keydown` and `keypress` events (i.e. not parsing any alphabetic input on numerical fields).

@jessepollak On release 2.3.0 I see that you merged a PR to hack fix this issue for the credit card field. What's your thought on rewriting core functionality of this library to work solely with the on `input` event which would ensure cross browser/platform functionality?

**Comment by jessepollak** [comment] 2017-09-12 00:27
I am definitely open to a refactor like this, that said I don't have the bandwidth to do it. If you want to go for it, I'd love to review!

**Closed** 2021-03-24 18:36 UTC
Labels: bug
